### ISSUE TITLE
gulp-rebase doesn't seem to rebase the img URLs in my HTML file

### ISSUE THREAD

**Issue by enginpost** [tunderdomb/rebase#1]
Am I doing something incorrectly or have I found a bug?

Here is my gulp file... https://bitbucket.org/enginpost/html-email/src/2bcad21d52630490177cdf0926f903a79d966435/gulpfile.js?at=master 

It never seems to rewrite the img urls.

**Comment by enginpost** [comment]
my bad ... I was doing it wrong. All is working fine. Thanks for a great package.

**Comment by tunderdomb** [comment]
I'm glad it is helpful to you.
